server:
  port: 8081

spring:
  security:
    user:
      name: user
      password: 1234

    oauth2:
      client:
        registration:
          google:
            client-id: 888592829652-7hu63c8fpsr3vqeg5f1vv66io5818bho.apps.googleusercontent.com
            client-secret: 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

          kakao:
            client-id: ab076f69d1063f7520e78fc0583f93c6
            client-secret: 4CtM4jkTEcdkL96CktWmllHBwbuZiMXE
            redirect-uri: http://localhost:8080/login/callback/kakao
            client-authentication-method: POST
            scope:

          naver:
            client-id: feB4tk5QZOMfyIJ7uLa6
            client-secret: rZ05YqONdw
            redirect-uri: http://localhost:8080/login/callback/naver
            scope:

          keycloak:
            client-id: oauth2-client-app
            client-name: oauth2-client-app
            client-secret: YYuqgjv4eC8nEbbxu24rEMlrFd5kSGk6
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile,email

        provider:
          google:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            user-name-attribute: preferred_username

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3299/security_oauth_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
